export enum FormTemplateErrorCode {
  NOT_FOUND = 'FORM_TEMPLATE_NOT_FOUND',
  FAILED_TO_SAVE = 'FORM_TEMPLATE_FAILED_TO_SAVE',
  FAILED_TO_DELETE = 'FORM_TEMPLATE_FAILED_TO_DELETE',
  FORBIDDEN = 'FORM_TEMPLATE_FORBIDDEN',
}
