export enum FormResponseErrorCode {
  NOT_FOUND = 'FORM_RESPONSE_NOT_FOUND',
  FAILED_TO_SAVE = 'FORM_RESPONSE_FAILED_TO_SAVE',
  FAILED_TO_DELETE = 'FORM_RESPONSE_FAILED_TO_DELETE',
  FORBIDDEN = 'FORM_RESPONSE_FORBIDDEN',
}
